### ISSUE TITLE
`gem release` returns 1 (error) always after a gem yank

### ISSUE THREAD

**Issue by justin808** [rubygems/rubygems.org#1577]
A week ago, I did a gem yank.

The problem is that with new versions, I keep getting an error:

```
Repushing of gem versions is not allowed.
Please use `gem yank` to remove bad gem releases.
rake aborted!
Command failed with status (1): [cd /Users/justin/shakacode/react-on-rails/...]
```

**However, it seems that new versions are still pushed!**

Here is my script output. 
```
cd /Users/justin/shakacode/react-on-rails/react_on_rails && gem release
WARNING:  open-ended dependency on gem-release (>= 0, development) is not recommended
  if gem-release is semantically versioned, use:
    add_development_dependency 'gem-release', '~> 0'
WARNING:  See http://guides.rubygems.org/specification-reference/ for help
  Successfully built RubyGem
  Name: react_on_rails
  Version: 6.8.0
  File: react_on_rails-6.8.0.gem
Pushing gem to https://rubygems.org...
Successfully registered gem: react_on_rails (6.8.0)
Deleting left over gem file react_on_rails-6.8.0.gem
WARNING:  See http://guides.rubygems.org/specification-reference/ for help
  Successfully built RubyGem
  Name: react_on_rails
  Version: 6.8.0
  File: react_on_rails-6.8.0.gem
Pushing gem to https://rubygems.org...
Repushing of gem versions is not allowed.
Please use `gem yank` to remove bad gem releases.
rake aborted!
Command failed with status (1): [cd /Users/justin/shakacode/react-on-rails/...]
/Users/justin/shakacode/react-on-rails/react_on_rails/rakelib/task_helpers.rb:20:in `block in sh_in_dir'
/Users/justin/shakacode/react-on-rails/react_on_rails/rakelib/task_helpers.rb:20:in `each'
/Users/justin/shakacode/react-on-rails/react_on_rails/rakelib/task_helpers.rb:20:in `sh_in_dir'
/Users/justin/shakacode/react-on-rails/react_on_rails/rakelib/release.rake:64:in `block in <top (required)>'
/Users/justin/.rvm/gems/ruby-2.3.1@react_on_rails/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
Tasks: TOP => release
(See full trace by running task with --trace)
```

**Comment by dwradcliffe** [comment]
This looks like a problem with `gem-release` (which is not an official part of rubygems). From the output it seems like it's trying to push the same gem twice. If you run this example twice it should either fail or use a different version number. (I'm not sure how gem-release works). I would suggest using the bundler rake tasks for pushing gems. (https://www.schneems.com/blogs/2016-03-18-bundler-release-tasks/)
