### ISSUE TITLE
rubygems.org has no AAAA record

### ISSUE THREAD

**Issue by m4z** [rubygems/rubygems.org#1612]
We use more and more servers that don't (and sometimes can't) have an IPv4 address.
rubygems.org seems to be unusable in this case:
```
myserver:/var/www/myapp # bundle install
Don't run Bundler as root. Bundler can ask for sudo if it is needed, and installing your bundle as root
will break this application for all non-root users on this machine.
Unfortunately, a fatal error has occurred. Please see the Bundler troubleshooting documentation at
http://bit.ly/bundler-issues. Thanks!
/usr/lib/ruby/2.1.0/net/http.rb:879:in `initialize': Network is unreachable - connect(2) for "bundler.rubygems.org" port 443 (Errno::ENETUNREACH)
	from /usr/lib/ruby/2.1.0/net/http.rb:879:in `open'
	from /usr/lib/ruby/2.1.0/net/http.rb:879:in `block in connect'
	from /usr/lib/ruby/2.1.0/timeout.rb:76:in `timeout'
	from /usr/lib/ruby/2.1.0/net/http.rb:878:in `connect'
	from /usr/lib/ruby/2.1.0/net/http.rb:863:in `do_start'
	from /usr/lib/ruby/2.1.0/net/http.rb:858:in `start'
	from /usr/lib/ruby/vendor_ruby/net/http/persistent.rb:691:in `start'
	from /usr/lib/ruby/vendor_ruby/net/http/persistent.rb:631:in `connection_for'
[…]
	from /usr/lib/ruby/vendor_ruby/bundler/cli.rb:9:in `start'
	from /usr/bin/bundle:20:in `block in <main>'
	from /usr/lib/ruby/vendor_ruby/bundler/friendly_errors.rb:5:in `with_friendly_errors'
	from /usr/bin/bundle:18:in `<main>'
myserver:/var/www/myapp # host -t AAAA bundler.rubygems.org
bundler.rubygems.org is an alias for rubygems.org.
myserver:/var/www/myapp # host -t AAAA rubygems.org
rubygems.org has no AAAA record
myserver:/var/www/myapp # ip -4 a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default 
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
myserver:/var/www/myapp # 
```

What can I do to make this work?

(Probably similar to #968, but that is closed, so I'm not touching that.)

**Comment by neopostmodern** [comment]
Looking at [this](http://help.rubygems.org/discussions/problems/31074-timeout-error) and [this](https://stackoverflow.com/questions/49800432/gem-cannot-access-rubygems-org/50349235#50349235) (which can be summarized as: on Ubuntu 18.04 and up manually altering configuration files to get gem to downgrade to IPv4 is necessary) I would think this should have a rather high priority?

Or if it's hard to fix it should *at least* include some informative error message (on gem's end of things).

**Comment by FlorinPopaCodes** [comment]
The problem stated in the title is no longer relevant. A new AAAA record was added for rubygems.org, but connecting to that ipv6 reaches a timeout.

```
wget https://rubygems.org/latest_specs.4.8.gz
--2019-02-21 22:42:14--  https://rubygems.org/latest_specs.4.8.gz
Loaded CA certificate '/etc/ssl/certs/ca-certificates.crt'
Resolving rubygems.org (rubygems.org)... 2a04:4e42::70, 151.101.128.70, 151.101.64.70, ...
Connecting to rubygems.org (rubygems.org)|2a04:4e42::70|:443... failed: Connection timed out.
Connecting to rubygems.org (rubygems.org)|151.101.128.70|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1261209 (1.2M) [application/octet-stream]
Saving to: ‘latest_specs.4.8.gz.1’

latest_specs.4.8.gz. 100%[======================>]   1.20M  4.09MB/s    in 0.3s    

2019-02-21 22:44:25 (4.09 MB/s) - ‘latest_specs.4.8.gz.1’ saved [1261209/1261209]
```

I was staring at the screen for minutes waiting for `gem install bundler` to finish.

**Comment by clarfon** [comment]
This appears to have been a problem for almost a year… could you please at least remove the incorrect AAAA record so that rubygems doesn't time out?

**Comment by indirect** [comment]
@clarfon you might want to either fix your IPv6 network or disable it. The AAAA record works:

```
$ curl -vvv -6 https://rubygems.org -o /dev/null -s
* Rebuilt URL to: https://rubygems.org/
*   Trying 2a04:4e42::70...
* TCP_NODELAY set
* Connected to rubygems.org (2a04:4e42::70) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
} [218 bytes data]
* TLSv1.2 (IN), TLS handshake, Server hello (2):
{ [108 bytes data]
* TLSv1.2 (IN), TLS handshake, Certificate (11):
{ [4883 bytes data]
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
{ [300 bytes data]
* TLSv1.2 (IN), TLS handshake, Server finished (14):
{ [4 bytes data]
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
} [37 bytes data]
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
} [1 bytes data]
* TLSv1.2 (OUT), TLS handshake, Finished (20):
} [16 bytes data]
* TLSv1.2 (IN), TLS change cipher, Client hello (1):
{ [1 bytes data]
* TLSv1.2 (IN), TLS handshake, Finished (20):
{ [16 bytes data]
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server accepted to use http/1.1
* Server certificate:
*  subject: C=US; ST=California; L=San Francisco; O=Fastly, Inc.; CN=l.ssl.fastly.net
*  start date: Apr 13 18:39:09 2018 GMT
*  expire date: Jun 11 18:15:41 2020 GMT
*  subjectAltName: host "rubygems.org" matched cert's "rubygems.org"
*  issuer: C=BE; O=GlobalSign nv-sa; CN=GlobalSign Organization Validation CA - SHA256 - G2
*  SSL certificate verify ok.
> GET / HTTP/1.1
> Host: rubygems.org
> User-Agent: curl/7.54.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Content-Type: text/html; charset=utf-8
< X-Frame-Options: SAMEORIGIN
< X-XSS-Protection: 1; mode=block
< X-Content-Type-Options: nosniff
< X-Download-Options: noopen
< X-Permitted-Cross-Domain-Policies: none
< Referrer-Policy: strict-origin-when-cross-origin
< Cache-Control: max-age=0, private, must-revalidate
< Content-Security-Policy: default-src 'self'; font-src 'self' https://fonts.gstatic.com; img-src 'self' https://secure.gaug.es https://gravatar.com https://secure.gravatar.com https://*.fastly-insights.com; object-src 'none'; script-src 'self' https://secure.gaug.es https://www.fastly-insights.com; style-src 'self' https://fonts.googleapis.com; connect-src https://s3-us-west-2.amazonaws.com/rubygems-dumps/ https://*.fastly-insights.com https://api.github.com
< Set-Cookie: _rubygems_session=2Qvh2iNg5b1Zb%2F54bynSilB3g7sMbGN%2BrI2mkKPNTQZVV31DpsFWg3JhWW0pH5TyBuwHzQbkP8oPfVWDhKaKOk4PGel%2F5T9PPhQMdJ4xotcd01KNWIUr%2BB40WJEXFDFR3Ly5T4SZs9bTdsrrhaM%3D--DmlMkktoGcSAzjdp--2hIixw0BRVGamHoIBVaSdQ%3D%3D; path=/; secure; HttpOnly
< X-Request-Id: 186ead19-11fa-498b-ab52-4800de3e864c
< X-Runtime: 0.010448
< Strict-Transport-Security: max-age=0; includeSubDomains
< X-Backend: F_Rails 54.186.104.15:443
< Transfer-Encoding: chunked
< Accept-Ranges: bytes
< Date: Sun, 09 Jun 2019 23:10:29 GMT
< Via: 1.1 varnish
< Connection: keep-alive
< X-Served-By: cache-pao17421-PAO
< X-Cache: MISS
< X-Cache-Hits: 0
< X-Timer: S1560121830.759033,VS0,VE34
< Vary: Accept-Encoding,Fastly-SSL
< ETag: "94855893ff7b6ca16e84dda6a1358122"
< Server: RubyGems.org
< 
{ [1209 bytes data]
* Connection #0 to host rubygems.org left intact
```

**Comment by clarfon** [comment]
You appear to be right… apologies. It appears that my access point had started acting up and I never noticed.
